// DOM elements
const chatBox = document.getElementById('chat-box');
const userInput = document.getElementById('user-input');
const sendBtn = document.getElementById('send-btn');

// Event listeners
sendBtn.addEventListener('click', handleUserMessage);
userInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') {
        handleUserMessage();
    }
});

// Knowledge base of universal truths and facts
const knowledgeBase = {
    // Scientific facts
    "earth is flat": {
        fact: "The Earth is not flat; it is an oblate spheroid (a sphere slightly flattened at the poles). This has been proven through numerous scientific observations, photographs from space, and measurements of Earth's curvature.",
        status: "false",
        sources: [{title: "NASA - Earth Fact Sheet", url: "https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html"}]
    },
    "water boils": {
        fact: "Water boils at 100 degrees Celsius (212 degrees Fahrenheit) at standard atmospheric pressure (1 atmosphere or 101.325 kilopascals). However, the boiling point changes with altitude and pressure.",
        status: "verified",
        sources: [{title: "NIST Chemistry WebBook", url: "https://webbook.nist.gov/chemistry/"}]
    },
    "gravity": {
        fact: "Gravity is one of the four fundamental forces of nature. On Earth, gravity causes objects to accelerate toward the center of the planet at approximately 9.8 m/s² (32.2 ft/s²). Gravity is what keeps us grounded and causes objects to fall when dropped.",
        status: "verified",
        sources: [{title: "NASA - What is Gravity?", url: "https://spaceplace.nasa.gov/what-is-gravity/en/"}]
    },
    "evolution": {
        fact: "Evolution is the process by which species of organisms change over time through genetic variations and natural selection. It's supported by extensive evidence from fossils, comparative anatomy, genetics, and direct observation of evolutionary changes in laboratories and nature.",
        status: "verified",
        sources: [{title: "National Academy of Sciences", url: "https://www.nationalacademies.org/evolution/"}]
    },
    "sun revolves around earth": {
        fact: "The Sun does not revolve around the Earth. Instead, the Earth and other planets in our solar system revolve around the Sun. This heliocentric model was proposed by Copernicus in the 16th century and has been confirmed by countless astronomical observations.",
        status: "false",
        sources: [{title: "NASA - Solar System Exploration", url: "https://solarsystem.nasa.gov/solar-system/sun/overview/"}]
    },
    
    // Temperature facts
    "sun is hot": {
        fact: "The Sun is indeed extremely hot. The surface temperature of the Sun is about 5,500°C (9,940°F), while its core temperature is around 15 million°C (27 million°F). This heat is generated by nuclear fusion reactions in which hydrogen atoms combine to form helium.",
        status: "verified",
        sources: [{title: "NASA - Sun Facts", url: "https://solarsystem.nasa.gov/solar-system/sun/in-depth/"}]
    },
    "sun is cold": {
        fact: "The Sun is not cold; it is extremely hot. The surface temperature of the Sun is about 5,500°C (9,940°F), while its core temperature is around 15 million°C (27 million°F). This heat is generated by nuclear fusion reactions in which hydrogen atoms combine to form helium.",
        status: "false",
        sources: [{title: "NASA - Sun Facts", url: "https://solarsystem.nasa.gov/solar-system/sun/in-depth/"}]
    },
    
    // Historical facts
    "moon landing": {
        fact: "NASA's Apollo 11 mission successfully landed the first humans on the Moon on July 20, 1969. Neil Armstrong and Buzz Aldrin walked on the lunar surface while Michael Collins orbited above. Five more successful Moon landings followed from 1969-1972.",
        status: "verified",
        sources: [{title: "NASA - Apollo 11 Mission", url: "https://www.nasa.gov/mission_pages/apollo/apollo-11"}]
    },
    "dinosaurs humans": {
        fact: "Dinosaurs and humans did not coexist. Non-avian dinosaurs went extinct about 65 million years ago during the Cretaceous-Paleogene extinction event, while modern humans (Homo sapiens) evolved much later, appearing around 300,000 years ago.",
        status: "false",
        sources: [{title: "Smithsonian National Museum of Natural History", url: "https://naturalhistory.si.edu/education/teaching-resources/paleontology/dinosaur-extinction"}]
    },
    "world war 2": {
        fact: "World War II was a global conflict that lasted from 1939 to 1945, involving many of the world's nations including all great powers, forming two opposing military alliances: the Allies and the Axis. It was the most widespread war in history, with more than 100 million people serving in military units.",
        status: "verified",
        sources: [{title: "National WWII Museum", url: "https://www.nationalww2museum.org/"}]
    },
    "holocaust": {
        fact: "The Holocaust was the systematic, state-sponsored persecution and murder of six million Jews and millions of others (including Roma, disabled people, political prisoners, and homosexuals) by the Nazi regime and its allies during World War II. It is one of the most well-documented genocides in history.",
        status: "verified",
        sources: [{title: "United States Holocaust Memorial Museum", url: "https://www.ushmm.org/"}]
    },
    
    // Mathematical truths
    "2+2=4": {
        fact: "2+2=4. This is a basic mathematical equality and is universally true in standard arithmetic.",
        status: "verified",
        sources: []
    },
    "1+1=2": {
        fact: "1+1=2. This is a fundamental mathematical truth in standard arithmetic and is used as the foundation for more complex mathematical principles.",
        status: "verified",
        sources: []
    },
    "1+1=3": {
        fact: "1+1 does not equal 3. The correct sum is 1+1=2, which is a fundamental mathematical truth in standard arithmetic.",
        status: "false",
        sources: []
    },
    "pi": {
        fact: "Pi (π) is the ratio of a circle's circumference to its diameter. It's approximately 3.14159, but is an irrational number that continues infinitely without repeating patterns. It's a fundamental constant in mathematics and appears in many formulas in physics and engineering.",
        status: "verified",
        sources: [{title: "Wolfram MathWorld - Pi", url: "https://mathworld.wolfram.com/Pi.html"}]
    },
    
    // Geography
    "capital of france": {
        fact: "The capital of France is Paris. It's the country's largest city and a global center for art, fashion, gastronomy, and culture.",
        status: "verified",
        sources: [{title: "Official France Tourism Website", url: "https://www.france.fr/en/paris"}]
    },
    "france": {
        fact: "France is a country in Western Europe with a population of about 67 million people. Its capital is Paris, and it's known for its art, culture, cuisine, and historical monuments like the Eiffel Tower.",
        status: "verified",
        sources: [{title: "Official France Tourism Website", url: "https://www.france.fr/en"}]
    },
    "continents": {
        fact: "There are seven continents on Earth: Africa, Antarctica, Asia, Europe, North America, Australia/Oceania, and South America. However, some geographical models consider Europe and Asia as a single continent called Eurasia, bringing the count to six.",
        status: "verified",
        sources: [{title: "National Geographic - Continents", url: "https://www.nationalgeographic.org/encyclopedia/continent/"}]
    },
    "tallest mountain": {
        fact: "Mount Everest is Earth's highest mountain above sea level, with its peak at 8,848.86 meters (29,031.7 feet) above sea level. It's located in the Mahalangur Himal sub-range of the Himalayas on the border between Nepal and China.",
        status: "verified",
        sources: [{title: "USGS - Mount Everest", url: "https://www.usgs.gov/faqs/how-tall-mount-everest"}]
    },
    
    // Health and Science
    "vaccines autism": {
        fact: "There is no credible scientific evidence that vaccines cause autism. This misconception stemmed from a discredited and retracted 1998 study. Multiple large-scale studies have found no link between vaccines and autism.",
        status: "false",
        sources: [{title: "CDC - Vaccines Do Not Cause Autism", url: "https://www.cdc.gov/vaccinesafety/concerns/autism.html"}]
    },
    "smoking health": {
        fact: "Smoking tobacco is harmful to health. It causes cancer, heart disease, stroke, lung diseases, diabetes, and chronic obstructive pulmonary disease (COPD), including emphysema and chronic bronchitis. It increases the risk for many other health conditions and is the leading cause of preventable death.",
        status: "verified",
        sources: [{title: "CDC - Health Effects of Cigarette Smoking", url: "https://www.cdc.gov/tobacco/data_statistics/fact_sheets/health_effects/effects_cig_smoking/index.htm"}]
    },
    "climate change": {
        fact: "Climate change is real and is primarily caused by human activities, particularly the burning of fossil fuels which increases heat-trapping greenhouse gases in Earth's atmosphere. There is overwhelming scientific consensus on this fact, with over 97% of actively publishing climate scientists agreeing.",
        status: "verified",
        sources: [{title: "NASA - Climate Change: Evidence", url: "https://climate.nasa.gov/evidence/"}]
    },
    "5g causes covid": {
        fact: "5G technology does not cause COVID-19. COVID-19 is caused by the SARS-CoV-2 virus, which is spread through respiratory droplets and aerosols from infected individuals. 5G is a wireless technology that uses radio waves and cannot create or transmit viruses.",
        status: "false",
        sources: [{title: "World Health Organization - 5G Mobile Networks and Health", url: "https://www.who.int/news-room/questions-and-answers/item/5g-mobile-networks-and-health"}]
    },

    // Additional universal truths
    "humans need oxygen": {
        fact: "Humans do need oxygen to survive. Oxygen is essential for cellular respiration, the process by which cells produce energy. Without oxygen, cells cannot function properly, and the body's tissues and organs begin to fail, leading to death within minutes.",
        status: "verified",
        sources: [{title: "National Library of Medicine - Oxygen", url: "https://pubchem.ncbi.nlm.nih.gov/element/Oxygen"}]
    },
    "time travel": {
        fact: "Time travel to the past, as depicted in science fiction, is not currently possible and may be physically impossible according to our current understanding of physics. However, time dilation (a form of 'time travel' to the future) is a proven phenomenon in which time passes at different rates for objects moving at different speeds or in different gravitational fields.",
        status: "false",
        sources: [{title: "Scientific American - Is Time Travel Possible?", url: "https://www.scientificamerican.com/article/is-time-travel-possible/"}]
    },
    "water is wet": {
        fact: "Whether water is wet is actually a complex philosophical and scientific question. Water molecules make other things wet by adhering to their surface, but whether water itself is wet depends on how we define 'wetness.' Some scientists argue that water isn't wet because wetness is the ability of a liquid to adhere to a surface, and water molecules are already surrounded by other water molecules.",
        status: "uncertain",
        sources: [{title: "Scientific American - Is Water Wet?", url: "https://www.scientificamerican.com/article/is-water-wet/"}]
    },
    "earth is round": {
        fact: "The Earth is indeed round, or more precisely, it's an oblate spheroid (slightly flattened at the poles and bulging at the equator). This has been known since ancient times and has been confirmed by countless observations, measurements, and photographs from space.",
        status: "verified",
        sources: [{title: "NASA - Earth's Shape and Gravity", url: "https://www.nasa.gov/feature/goddard/2019/how-earth-s-gravity-is-changing"}]
    }
};

// Antonyms or opposites for better matching
const opposites = {
    "hot": "cold",
    "cold": "hot",
    "flat": "round",
    "round": "flat",
    "true": "false",
    "false": "true",
    "yes": "no",
    "no": "yes",
    "wet": "dry",
    "dry": "wet"
};

// Handle user messages
function handleUserMessage() {
    const message = userInput.value.trim();
    
    if (message === '') return;
    
    // Display user message
    displayMessage(message, 'user');
    
    // Clear input
    userInput.value = '';
    
    // Show typing indicator
    showTypingIndicator();
    
    // Process and respond with a slight delay to simulate thinking
    setTimeout(() => {
        processUserMessage(message);
    }, 1000);
}

// Display message in chat
function displayMessage(message, sender, sources = null, factStatus = null) {
    const messageDiv = document.createElement('div');
    messageDiv.classList.add('chat-message', sender);
    
    const contentDiv = document.createElement('div');
    contentDiv.classList.add('message-content');
    
    // Add fact status indicator if present
    if (sender === 'bot' && factStatus) {
        const statusDiv = document.createElement('div');
        statusDiv.classList.add('fact-status', `fact-${factStatus.type}`);
        statusDiv.textContent = factStatus.text;
        contentDiv.appendChild(statusDiv);
    }
    
    // Process message text
    if (sender === 'bot' && typeof message === 'string') {
        // Convert URLs to clickable links
        const urlRegex = /(https?:\/\/[^\s]+)/g;
        const textWithLinks = message.replace(urlRegex, (url) => {
            return `<a href="${url}" target="_blank" rel="noopener noreferrer">${url}</a>`;
        });
        
        const messageP = document.createElement('p');
        messageP.innerHTML = textWithLinks;
        contentDiv.appendChild(messageP);
    } else {
        const paragraph = document.createElement('p');
        paragraph.textContent = message;
        contentDiv.appendChild(paragraph);
    }
    
    // Add sources if available
    if (sources && sources.length > 0) {
        const sourcesDiv = document.createElement('div');
        sourcesDiv.classList.add('sources');
        
        const sourcesTitle = document.createElement('p');
        sourcesTitle.textContent = 'Sources:';
        sourcesTitle.classList.add('sources-title');
        sourcesDiv.appendChild(sourcesTitle);
        
        const sourcesList = document.createElement('ul');
        sources.forEach(source => {
            const sourceItem = document.createElement('li');
            const sourceLink = document.createElement('a');
            sourceLink.href = source.url;
            sourceLink.textContent = source.title || source.url;
            sourceLink.target = '_blank';
            sourceLink.rel = 'noopener noreferrer';
            sourceItem.appendChild(sourceLink);
            sourcesList.appendChild(sourceItem);
        });
        
        sourcesDiv.appendChild(sourcesList);
        contentDiv.appendChild(sourcesDiv);
    }
    
    messageDiv.appendChild(contentDiv);
    chatBox.appendChild(messageDiv);
    
    // Scroll to bottom
    chatBox.scrollTop = chatBox.scrollHeight;
}

// Show typing indicator
function showTypingIndicator() {
    const typingDiv = document.createElement('div');
    typingDiv.classList.add('chat-message', 'bot', 'typing-indicator-container');
    typingDiv.id = 'typing-indicator';
    
    const contentDiv = document.createElement('div');
    contentDiv.classList.add('message-content');
    
    const indicator = document.createElement('div');
    indicator.classList.add('typing-indicator');
    
    for (let i = 0; i < 3; i++) {
        const dot = document.createElement('span');
        indicator.appendChild(dot);
    }
    
    contentDiv.appendChild(indicator);
    typingDiv.appendChild(contentDiv);
    chatBox.appendChild(typingDiv);
    
    // Scroll to bottom
    chatBox.scrollTop = chatBox.scrollHeight;
}

// Remove typing indicator
function removeTypingIndicator() {
    const typingIndicator = document.getElementById('typing-indicator');
    if (typingIndicator) {
        typingIndicator.remove();
    }
}

// Check if a statement is an opposite/negation of a known fact
function checkForOpposites(message) {
    const words = message.split(/\s+/);
    
    for (const key in knowledgeBase) {
        const keyWords = key.split(/\s+/);
        
        // For simple cases like "sun is cold" when we know "sun is hot"
        if (words.length >= 3 && keyWords.length >= 3) {
            // Check if the subject matches and only the property differs
            if (words[0] === keyWords[0] && words[1] === keyWords[1]) {
                // Check if the properties are opposites
                if (opposites[words[2]] === keyWords[2] || opposites[keyWords[2]] === words[2]) {
                    // If we found an opposite, return the opposite fact status
                    const fact = { ...knowledgeBase[key] };
                    if (fact.status === "verified") {
                        fact.status = "false";
                    } else if (fact.status === "false") {
                        fact.status = "verified";
                    }
                    return fact;
                }
            }
        }
    }
    
    return null;
}

// Check mathematical expressions
function checkMathExpression(message) {
    // Check for basic arithmetic expressions like "1+1=5"
    const mathPattern = /(\d+)\s*(\+|\-|\*|\/)\s*(\d+)\s*=\s*(\d+)/i;
    const match = message.match(mathPattern);
    
    if (match) {
        const num1 = parseInt(match[1]);
        const operator = match[2];
        const num2 = parseInt(match[3]);
        const claimed = parseInt(match[4]);
        
        let result;
        switch (operator) {
            case '+': result = num1 + num2; break;
            case '-': result = num1 - num2; break;
            case '*': result = num1 * num2; break;
            case '/': result = num1 / num2; break;
        }
        
        if (result === claimed) {
            return {
                fact: `${num1}${operator}${num2}=${claimed} is correct. This is a basic mathematical fact in standard arithmetic.`,
                status: "verified",
                sources: []
            };
        } else {
            return {
                fact: `${num1}${operator}${num2}=${claimed} is incorrect. The correct answer is ${num1}${operator}${num2}=${result}. This is a basic mathematical fact in standard arithmetic.`,
                status: "false",
                sources: []
            };
        }
    }
    
    return null;
}

// Process user message and find response
function processUserMessage(message) {
    // Convert to lowercase for better matching
    const lowerMessage = message.toLowerCase();
    
    // Remove typing indicator
    removeTypingIndicator();
    
    // Check if the message is a greeting
    if (lowerMessage.match(/\b(hello|hi|hey|greetings|howdy)\b/i)) {
        // Simple greeting response
        displayMessage("Hello! I'm your AI Fact Checker. Ask me about science, history, geography, or check if something is true or false. How can I help you today?", 'bot');
        return;
    }
    
    // Check if it's a thank you message
    if (lowerMessage.match(/\b(thank|thanks)\b/i)) {
        // Appreciation response
        displayMessage("You're welcome! Feel free to ask me about more facts anytime.", 'bot');
        return;
    }
    
    // Check if user is asking about the bot itself
    if (lowerMessage.match(/\b(who are you|what are you|how do you work|tell me about yourself)\b/i)) {
        // Self-identification
        displayMessage("I'm an AI Fact Checker designed to provide verified information on various topics. I have a knowledge base about science, history, mathematics, geography, and other subjects. I can tell you whether something is true or false based on established facts.", 'bot');
        return;
    }
    
    // First check if it's a mathematical expression
    let matchedFact = checkMathExpression(lowerMessage);
    
    // If not a math expression, check direct matches in the knowledge base
    if (!matchedFact) {
        matchedFact = findRelevantFact(lowerMessage);
    }
    
    // If no direct match, check for opposites or negations
    if (!matchedFact) {
        matchedFact = checkForOpposites(lowerMessage);
    }
    
    if (matchedFact) {
        // Determine fact status
        let factStatus;
        if (matchedFact.status === "verified") {
            factStatus = {
                type: 'verified',
                text: 'Verified ✓'
            };
        } else if (matchedFact.status === "false") {
            factStatus = {
                type: 'false',
                text: 'False ✗'
            };
        } else {
            factStatus = {
                type: 'uncertain',
                text: 'Uncertain ⚠'
            };
        }
        
        // Display message with fact and sources
        displayMessage(matchedFact.fact, 'bot', matchedFact.sources, factStatus);
    } else {
        // Check if it's a true/false question
        if (lowerMessage.match(/\b(is it true|is that true|is this true|true or false)\b/i)) {
            displayMessage(
                "I don't have specific information about that statement in my knowledge base. For accurate fact-checking, try being more specific about the claim you want to verify.",
                'bot',
                [],
                { type: 'uncertain', text: 'Information Limited' }
            );
        } else {
            // Default response for unknown questions
            displayMessage(
                "I don't have specific information about that in my knowledge base. Try asking about topics like 'climate change', 'vaccines and autism', 'the Earth is flat', 'moon landing', 'dinosaurs and humans', or other basic scientific and historical facts.",
                'bot',
                [],
                { type: 'uncertain', text: 'Information Limited' }
            );
        }
    }
}

// Find the most relevant fact from knowledge base
function findRelevantFact(message) {
    // Direct keyword matching - check if any knowledge base key is entirely in the message
    for (const key in knowledgeBase) {
        if (message.includes(key)) {
            return knowledgeBase[key];
        }
    }
    
    // Check for question patterns with key terms
    const questionPatterns = [
        /\b(what|tell|explain|how|who|when|where|why|which|is|are|was|were|do|does|did|can|could|has|have|had)\b/i
    ];
    
    for (const pattern of questionPatterns) {
        if (pattern.test(message)) {
            // If it's a question, look for keyword matches
            for (const key in knowledgeBase) {
                const keyTerms = key.split(' ');
                // Check if any significant term from the key is in the message
                for (const term of keyTerms) {
                    if (term.length > 2 && message.includes(term)) {
                        return knowledgeBase[key];
                    }
                }
            }
        }
    }
    
    // Check for true/false patterns with key terms
    if (message.match(/\b(true|false|fact|truth|lie|correct|wrong|real|fake)\b/i)) {
        for (const key in knowledgeBase) {
            const keyTerms = key.split(' ');
            for (const term of keyTerms) {
                if (term.length > 2 && message.includes(term)) {
                    return knowledgeBase[key];
                }
            }
        }
    }
    
    return null;
} 